name: Deploy Fabric

on:
  pull_request:
    types:
      - closed
    
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dev
    env:
      # Set these as GitHub secrets or environment variables in your repo
      fabricBaseUrl: ${{ secrets.fabricBaseUrl }}
      clientId: ${{ secrets.clientId }}
      tenantId: ${{ secrets.tenantId }}
      servicePrincipalSecret: ${{ secrets.servicePrincipalSecret }}
      workspaceName: ${{ secrets.workspaceName }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Source Workspace from GIT
        shell: pwsh
        run: |
          ./devops/update-ws-from-git.ps1 `
            -fabricBaseUrl "${{ env.fabricBaseUrl }}" `
            -clientId "${{ env.fabricBaseUrl }}" `
            -tenantId "${{ env.tenantId }}" `
            -servicePrincipalSecret "${{ env.servicePrincipalSecret }}" `
            -workspaceName "${{ env.workspaceName }}"
